"""add notification table

Revision ID: 00f800b106b9
Revises: c3d4e5f6a7b3
Create Date: 2026-06-26 11:37:15.143910

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '00f800b106b9'
down_revision: str | Sequence[str] | None = 'c3d4e5f6a7b3'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Notification',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('institute_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.Enum('FEE_REMINDER', 'FEE_RECEIPT', 'ABSENCE', 'ENROLLMENT_INVITE', name='notificationtype'), nullable=False),
    sa.Column('status', sa.Enum('SENT', 'SKIPPED_UNVERIFIED', 'FAILED', name='notificationstatus'), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['institute_id'], ['Institute.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['Parent.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['Student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Notification_id'), 'Notification', ['id'], unique=False)
    op.create_index('ix_notification_institute_id', 'Notification', ['institute_id'], unique=False)
    op.create_index('ix_notification_student_id', 'Notification', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_notification_student_id', table_name='Notification')
    op.drop_index('ix_notification_institute_id', table_name='Notification')
    op.drop_index(op.f('ix_Notification_id'), table_name='Notification')
    op.drop_table('Notification')
    # ### end Alembic commands ###
