"""fix institute slug index naming

Revision ID: 0ccc849e3070
Revises: d4e5f6a7b8c9
Create Date: 2026-07-07 17:13:43.372897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ccc849e3070'
down_revision: Union[str, Sequence[str], None] = 'd4e5f6a7b8c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_institute_slug'), table_name='Institute')
    op.drop_constraint(op.f('uq_institute_slug'), 'Institute', type_='unique')
    op.create_index(op.f('ix_Institute_slug'), 'Institute', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Institute_slug'), table_name='Institute')
    op.create_unique_constraint(op.f('uq_institute_slug'), 'Institute', ['slug'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_institute_slug'), 'Institute', ['slug'], unique=False)
    # ### end Alembic commands ###
