"""made user id and phone nuber unique

Revision ID: 0df67f0c3473
Revises: 292a642bc3e5
Create Date: 2026-04-17 09:49:26.097650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0df67f0c3473'
down_revision: Union[str, Sequence[str], None] = '292a642bc3e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Student_phone_number'), table_name='Student')
    op.drop_index(op.f('ix_Student_user_id'), table_name='Student')
    op.create_unique_constraint(None, 'Student', ['user_id'])
    op.create_unique_constraint(None, 'Student', ['phone_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Student', type_='unique')
    op.drop_constraint(None, 'Student', type_='unique')
    op.create_index(op.f('ix_Student_user_id'), 'Student', ['user_id'], unique=False)
    op.create_index(op.f('ix_Student_phone_number'), 'Student', ['phone_number'], unique=False)
    # ### end Alembic commands ###
