"""made user id as uuid string that is linked to the phone nubmer verification table

Revision ID: 1d57a9b01124
Revises: 0df67f0c3473
Create Date: 2026-05-03 22:54:19.947028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d57a9b01124'
down_revision: Union[str, Sequence[str], None] = '0df67f0c3473'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Student', 'user_id',
               existing_type=sa.VARCHAR(),
               type_=sa.UUID(),
               nullable=False,
               postgresql_using='user_id::uuid')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Student', 'user_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
