"""fixed the connectiong flow of student and owner

Revision ID: 2530741662dc
Revises: h2i3j4k5l6m7
Create Date: 2026-06-15 09:34:09.227269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2530741662dc'
down_revision: Union[str, Sequence[str], None] = 'h2i3j4k5l6m7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_institute_join_code'), table_name='Institute')
    op.drop_constraint(op.f('uq_institute_join_code'), 'Institute', type_='unique')
    op.create_index(op.f('ix_Institute_join_code'), 'Institute', ['join_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Institute_join_code'), table_name='Institute')
    op.create_unique_constraint(op.f('uq_institute_join_code'), 'Institute', ['join_code'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_institute_join_code'), 'Institute', ['join_code'], unique=False)
    # ### end Alembic commands ###
