"""added user_id column to the database

Revision ID: 292a642bc3e5
Revises: b683bc8c3be4
Create Date: 2026-04-17 09:28:50.077172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '292a642bc3e5'
down_revision: Union[str, Sequence[str], None] = 'b683bc8c3be4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Student',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('fees_status', sa.Enum('FULLY_PAID', 'PARTIALLY_PAID', 'NOT_PAID', name='studentfeesstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Student_id'), 'Student', ['id'], unique=False)
    op.create_index(op.f('ix_Student_phone_number'), 'Student', ['phone_number'], unique=False)
    op.create_index(op.f('ix_Student_user_id'), 'Student', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Student_user_id'), table_name='Student')
    op.drop_index(op.f('ix_Student_phone_number'), table_name='Student')
    op.drop_index(op.f('ix_Student_id'), table_name='Student')
    op.drop_table('Student')
    # ### end Alembic commands ###
