"""add unique constraint on class session batch and date

Revision ID: 350e70addbde
Revises: 0ccc849e3070
Create Date: 2026-07-07 17:41:17.926515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '350e70addbde'
down_revision: Union[str, Sequence[str], None] = '0ccc849e3070'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_class_session_batch_date', 'ClassSession', ['batch_id', 'date'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_class_session_batch_date', 'ClassSession', type_='unique')
    # ### end Alembic commands ###
