"""added email column to student table

Revision ID: 4ceb025229b0
Revises: f8ed45d72bec
Create Date: 2026-04-07 00:33:31.264501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ceb025229b0'
down_revision: Union[str, Sequence[str], None] = 'f8ed45d72bec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Student', sa.Column('email', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Student', 'email')
    # ### end Alembic commands ###
