"""creating fresh tables

Revision ID: 8a79669dfe07
Revises: f7a3a8269016
Create Date: 2026-06-15 10:01:10.863528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a79669dfe07'
down_revision: Union[str, Sequence[str], None] = 'f7a3a8269016'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Owner',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('teacher_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('institute_name', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_number'),
    sa.UniqueConstraint('teacher_id')
    )
    op.create_index(op.f('ix_Owner_id'), 'Owner', ['id'], unique=False)
    op.create_table('Institute',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('join_code', sa.String(length=8), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['Owner.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id')
    )
    op.create_index(op.f('ix_Institute_id'), 'Institute', ['id'], unique=False)
    op.create_index(op.f('ix_Institute_join_code'), 'Institute', ['join_code'], unique=True)
    op.create_table('Batch',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('institute_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('grade', sa.String(), nullable=True),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('days_of_week', sa.JSON(), nullable=False),
    sa.Column('max_capacity', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'CLOSING', 'ARCHIVED', name='batchstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['institute_id'], ['Institute.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Batch_id'), 'Batch', ['id'], unique=False)
    op.create_table('Parent',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('institute_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['institute_id'], ['Institute.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_number'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_Parent_id'), 'Parent', ['id'], unique=False)
    op.create_table('Teacher',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('institute_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['institute_id'], ['Institute.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_number'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_Teacher_id'), 'Teacher', ['id'], unique=False)
    op.create_table('BatchTeacher',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['Batch.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['Teacher.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('batch_id', 'teacher_id', name='uq_batch_teacher')
    )
    op.create_index(op.f('ix_BatchTeacher_id'), 'BatchTeacher', ['id'], unique=False)
    op.create_table('ClassSession',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('topic', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['Batch.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ClassSession_id'), 'ClassSession', ['id'], unique=False)
    op.create_table('FeeStructure',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('monthly_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['Batch.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('batch_id', name='uq_fee_structure_batch')
    )
    op.create_index(op.f('ix_FeeStructure_id'), 'FeeStructure', ['id'], unique=False)
    op.create_table('Student',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('fees_status', sa.Enum('FULLY_PAID', 'PARTIALLY_PAID', 'NOT_PAID', name='studentfeesstatus'), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('institute_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['institute_id'], ['Institute.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['Parent.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Student_id'), 'Student', ['id'], unique=False)
    op.create_table('Enrollment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('enrolled_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('due_day', sa.Integer(), nullable=False),
    sa.Column('first_month_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['Batch.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['Student.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'batch_id', name='uq_enrollment_student_batch')
    )
    op.create_index(op.f('ix_Enrollment_id'), 'Enrollment', ['id'], unique=False)
    op.create_table('Attendance',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('enrollment_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PRESENT', 'ABSENT', 'LATE', name='attendancestatus'), nullable=False),
    sa.Column('marked_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['enrollment_id'], ['Enrollment.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['ClassSession.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'enrollment_id', name='uq_attendance_session_enrollment')
    )
    op.create_index(op.f('ix_Attendance_id'), 'Attendance', ['id'], unique=False)
    op.create_table('FeeRecord',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('enrollment_id', sa.Integer(), nullable=False),
    sa.Column('month', sa.Date(), nullable=False),
    sa.Column('amount_due', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('amount_paid', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('NOT_PAID', 'PARTIALLY_PAID', 'FULLY_PAID', name='feestatus'), nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('payment_reference', sa.String(), nullable=True),
    sa.Column('payment_link', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['enrollment_id'], ['Enrollment.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('enrollment_id', 'month', name='uq_fee_record_enrollment_month')
    )
    op.create_index(op.f('ix_FeeRecord_id'), 'FeeRecord', ['id'], unique=False)
    op.create_table('TestScore',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('enrollment_id', sa.Integer(), nullable=False),
    sa.Column('test_name', sa.String(), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('max_marks', sa.Integer(), nullable=False),
    sa.Column('obtained_marks', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['enrollment_id'], ['Enrollment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_TestScore_id'), 'TestScore', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_TestScore_id'), table_name='TestScore')
    op.drop_table('TestScore')
    op.drop_index(op.f('ix_FeeRecord_id'), table_name='FeeRecord')
    op.drop_table('FeeRecord')
    op.drop_index(op.f('ix_Attendance_id'), table_name='Attendance')
    op.drop_table('Attendance')
    op.drop_index(op.f('ix_Enrollment_id'), table_name='Enrollment')
    op.drop_table('Enrollment')
    op.drop_index(op.f('ix_Student_id'), table_name='Student')
    op.drop_table('Student')
    op.drop_index(op.f('ix_FeeStructure_id'), table_name='FeeStructure')
    op.drop_table('FeeStructure')
    op.drop_index(op.f('ix_ClassSession_id'), table_name='ClassSession')
    op.drop_table('ClassSession')
    op.drop_index(op.f('ix_BatchTeacher_id'), table_name='BatchTeacher')
    op.drop_table('BatchTeacher')
    op.drop_index(op.f('ix_Teacher_id'), table_name='Teacher')
    op.drop_table('Teacher')
    op.drop_index(op.f('ix_Parent_id'), table_name='Parent')
    op.drop_table('Parent')
    op.drop_index(op.f('ix_Batch_id'), table_name='Batch')
    op.drop_table('Batch')
    op.drop_index(op.f('ix_Institute_join_code'), table_name='Institute')
    op.drop_index(op.f('ix_Institute_id'), table_name='Institute')
    op.drop_table('Institute')
    op.drop_index(op.f('ix_Owner_id'), table_name='Owner')
    op.drop_table('Owner')
    # ### end Alembic commands ###
