"""added user_id column to the database

Revision ID: b683bc8c3be4
Revises: edb537b7e444
Create Date: 2026-04-17 09:19:51.580253

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b683bc8c3be4'
down_revision: Union[str, Sequence[str], None] = 'edb537b7e444'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Student_id'), table_name='Student')
    op.drop_index(op.f('ix_Student_phone_number'), table_name='Student')
    op.drop_table('Student')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Student',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('fees_status', postgresql.ENUM('FULLY_PAID', 'PARTIALLY_PAID', 'NOT_PAID', name='studentfeesstatus'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('phone_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('Student_pkey'))
    )
    op.create_index(op.f('ix_Student_phone_number'), 'Student', ['phone_number'], unique=False)
    op.create_index(op.f('ix_Student_id'), 'Student', ['id'], unique=False)
    # ### end Alembic commands ###
