"""change the name of phone -> phone_number

Revision ID: edb537b7e444
Revises: 4ceb025229b0
Create Date: 2026-04-07 01:08:02.343618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edb537b7e444'
down_revision: Union[str, Sequence[str], None] = '4ceb025229b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Student', sa.Column('phone_number', sa.String(), nullable=True))
    op.drop_index(op.f('ix_Student_phone'), table_name='Student')
    op.create_index(op.f('ix_Student_phone_number'), 'Student', ['phone_number'], unique=False)
    op.drop_column('Student', 'phone')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Student', sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_Student_phone_number'), table_name='Student')
    op.create_index(op.f('ix_Student_phone'), 'Student', ['phone'], unique=False)
    op.drop_column('Student', 'phone_number')
    # ### end Alembic commands ###
