"""init schema

Revision ID: f8ed45d72bec
Revises: a28903a64a0f
Create Date: 2026-04-06 23:56:28.987813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8ed45d72bec'
down_revision: Union[str, Sequence[str], None] = 'a28903a64a0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Student',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('fees_status', sa.Enum('FULLY_PAID', 'PARTIALLY_PAID', 'NOT_PAID', name='studentfeesstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Student_id'), 'Student', ['id'], unique=False)
    op.create_index(op.f('ix_Student_phone'), 'Student', ['phone_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Student_phone'), table_name='Student')
    op.drop_index(op.f('ix_Student_id'), table_name='Student')
    op.drop_table('Student')
    # ### end Alembic commands ###
